/**
 * Global Equivalent Domains
 * 
 * Bitwarden's predefined list of domain groups that share credentials.
 * These are commonly used services where multiple domains represent the same login.
 * 
 * Reference: https://github.com/bitwarden/server
 */

export interface GlobalDomain {
    type: number
    domains: string[]
}

// Bitwarden's global equivalent domain types
export const GLOBAL_EQUIVALENT_DOMAINS: GlobalDomain[] = [
    { type: 0, domains: ['youtube.com', 'google.com', 'gmail.com'] },
    { type: 1, domains: ['apple.com', 'icloud.com'] },
    { type: 2, domains: ['amazon.com', 'amazon.co.uk', 'amazon.ca', 'amazon.de', 'amazon.fr', 'amazon.es', 'amazon.it', 'amazon.co.jp', 'amazon.com.au', 'amazon.com.br', 'amazon.cn', 'amazon.in'] },
    { type: 3, domains: ['live.com', 'microsoft.com', 'microsoftonline.com', 'office.com', 'office365.com', 'outlook.com', 'passport.net', 'hotmail.com', 'xbox.com', 'azure.com'] },
    { type: 4, domains: ['accounts.google.com', 'google.com', 'youtube.com', 'gmail.com', 'googlemail.com'] },
    { type: 5, domains: ['bing.com', 'microsoft.com', 'live.com', 'outlook.com'] },
    { type: 6, domains: ['nytimes.com', 'nyti.ms'] },
    { type: 7, domains: ['booking.com', 'priceline.com', 'kayak.com', 'agoda.com', 'opentable.com'] },
    { type: 8, domains: ['facebook.com', 'messenger.com', 'fb.com'] },
    { type: 9, domains: ['instagram.com', 'facebook.com', 'threads.net'] },
    { type: 10, domains: ['whatsapp.com', 'facebook.com'] },
    { type: 11, domains: ['dropbox.com', 'getdropbox.com'] },
    { type: 12, domains: ['discord.com', 'discordapp.com'] },
    { type: 13, domains: ['roblox.com', 'rbxcdn.com'] },
    { type: 14, domains: ['yahoo.com', 'yahoo.co.jp', 'yahoo.co.uk', 'rogers.com'] },
    { type: 15, domains: ['steam.com', 'steampowered.com', 'steamcommunity.com'] },
    { type: 16, domains: ['ea.com', 'origin.com'] },
    { type: 17, domains: ['epicgames.com', 'unrealengine.com'] },
    { type: 18, domains: ['github.com', 'github.dev', 'githubusercontent.com'] },
    { type: 19, domains: ['gitlab.com', 'gitlab.io'] },
    { type: 20, domains: ['linkedin.com', 'lnkd.in'] },
    { type: 21, domains: ['netflix.com', 'nflxext.com'] },
    { type: 22, domains: ['paypal.com', 'paypal.me'] },
    { type: 23, domains: ['reddit.com', 'redd.it'] },
    { type: 24, domains: ['slack.com', 'slackb.com'] },
    { type: 25, domains: ['spotify.com', 'spotify.net'] },
    { type: 26, domains: ['twitch.tv', 'twitchcdn.net'] },
    { type: 27, domains: ['twitter.com', 'x.com'] },
    { type: 28, domains: ['zoom.us', 'zoom.com'] },
    { type: 29, domains: ['adobe.com', 'behance.net', 'magento.com'] },
    { type: 30, domains: ['atlassian.com', 'atlassian.net', 'bitbucket.org', 'trello.com', 'statuspage.io'] },
    { type: 31, domains: ['chase.com', 'jpmorgan.com'] },
    { type: 32, domains: ['citibank.com', 'citi.com'] },
    { type: 33, domains: ['bankofamerica.com', 'bofa.com'] },
    { type: 34, domains: ['wellsfargo.com', 'wf.com'] },
    { type: 35, domains: ['capitalone.com', 'capitalone360.com'] },
    { type: 36, domains: ['americanexpress.com', 'amex.com'] },
    { type: 37, domains: ['discover.com', 'discovercard.com'] },
    { type: 38, domains: ['usaa.com', 'usaa.net'] },
    { type: 39, domains: ['vanguard.com', 'vanguardinvestments.com'] },
    { type: 40, domains: ['fidelity.com', 'netbenefits.com'] },
    { type: 41, domains: ['schwab.com', 'schwaballiance.com'] },
    { type: 42, domains: ['ebay.com', 'ebay.co.uk', 'ebay.de', 'ebay.fr', 'ebay.ca', 'ebay.com.au'] },
    { type: 43, domains: ['etsy.com', 'etsystatic.com'] },
    { type: 44, domains: ['walmart.com', 'samsclub.com'] },
    { type: 45, domains: ['target.com', 'targetcircle.com'] },
    { type: 46, domains: ['bestbuy.com', 'bestbuycanada.ca'] },
    { type: 47, domains: ['homedepot.com', 'homedepot.ca'] },
    { type: 48, domains: ['lowes.com', 'lowes.ca'] },
    { type: 49, domains: ['costco.com', 'costco.ca'] },
    { type: 50, domains: ['uber.com', 'ubereats.com'] },
    { type: 51, domains: ['lyft.com', 'lyftassets.com'] },
    { type: 52, domains: ['airbnb.com', 'airbnb.co.uk', 'airbnb.ca'] },
    { type: 53, domains: ['expedia.com', 'hotels.com', 'vrbo.com', 'travelocity.com', 'trivago.com'] },
    { type: 54, domains: ['tripadvisor.com', 'viator.com'] },
    { type: 55, domains: ['southwest.com', 'swabiz.com'] },
    { type: 56, domains: ['aa.com', 'aadvantage.com'] },
    { type: 57, domains: ['united.com', 'ual.com', 'mileageplus.com'] },
    { type: 58, domains: ['delta.com', 'delta.com.mx'] },
    { type: 59, domains: ['jetblue.com', 'trueblue.com'] },
    { type: 60, domains: ['marriott.com', 'starwoodhotels.com', 'spg.com'] },
    { type: 61, domains: ['hilton.com', 'hiltonhonors.com'] },
    { type: 62, domains: ['hyatt.com', 'worldofhyatt.com'] },
    { type: 63, domains: ['ihg.com', 'holiday-inn.com', 'intercontinental.com'] },
    { type: 64, domains: ['doordash.com', 'doordash.xyz'] },
    { type: 65, domains: ['grubhub.com', 'seamless.com'] },
    { type: 66, domains: ['postmates.com', 'uber.com'] },
    { type: 67, domains: ['instacart.com', 'instacartassets.com'] },
    { type: 68, domains: ['shipt.com', 'target.com'] },
    { type: 69, domains: ['hulu.com', 'huluim.com'] },
    { type: 70, domains: ['hbo.com', 'hbomax.com', 'max.com'] },
    { type: 71, domains: ['disneyplus.com', 'disney.com', 'go.com'] },
    { type: 72, domains: ['paramount.com', 'paramountplus.com', 'cbs.com', 'cbsinteractive.com'] },
    { type: 73, domains: ['peacocktv.com', 'nbcuniversal.com'] },
    { type: 74, domains: ['crunchyroll.com', 'vrv.co'] },
    { type: 75, domains: ['nintendo.com', 'nintendo.net', 'nintendo.co.jp'] },
    { type: 76, domains: ['playstation.com', 'sonyentertainmentnetwork.com', 'sony.com'] },
    { type: 77, domains: ['xbox.com', 'microsoft.com', 'xboxlive.com'] },
    { type: 78, domains: ['blizzard.com', 'battle.net', 'activision.com'] },
    { type: 79, domains: ['riotgames.com', 'leagueoflegends.com'] },
    { type: 80, domains: ['ubisoft.com', 'ubi.com'] },
    { type: 81, domains: ['sq1.com', 'squareup.com', 'cash.app'] },
    { type: 82, domains: ['venmo.com', 'paypal.com'] },
    { type: 83, domains: ['zelle.com', 'zellepay.com'] },
    { type: 84, domains: ['coinbase.com', 'coinbase.pro'] },
    { type: 85, domains: ['robinhood.com', 'robinhood.io'] },
    { type: 86, domains: ['etrade.com', 'morganstanley.com'] },
    { type: 87, domains: ['tdameritrade.com', 'thinkorswim.com', 'schwab.com'] },
    { type: 88, domains: ['binance.com', 'binance.us'] },
    { type: 89, domains: ['kraken.com', 'kraken.io'] },
    { type: 90, domains: ['cloudflare.com', 'cloudflare.net'] },
    { type: 91, domains: ['aws.amazon.com', 'amazon.com', 'amazonaws.com'] },
    { type: 92, domains: ['azure.com', 'microsoft.com', 'windowsazure.com'] },
    { type: 93, domains: ['cloud.google.com', 'google.com', 'googleapis.com'] },
    { type: 94, domains: ['digitalocean.com', 'digitaloceanspaces.com'] },
    { type: 95, domains: ['linode.com', 'akamai.com'] },
    { type: 96, domains: ['heroku.com', 'salesforce.com'] },
    { type: 97, domains: ['vercel.com', 'vercel.app'] },
    { type: 98, domains: ['netlify.com', 'netlify.app'] },
    { type: 99, domains: ['notion.so', 'notion.site'] },
]
